name: Contract Testing CI

on:
  push:
    branches: [ main ]

jobs:
  contract-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm install

      - name: Start json-server
        run: |
          npx json-server --watch db.json --port 4000 &
          sleep 5  

      - name: Start provider state setup server
        run: |
          node providerStates.js &
          sleep 2

      - name: Run Pact consumer tests
        run: npx jest pact/users.test.js

      - name: Install Ruby and Pact Verifier
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          
      - name: Install pact gem
        run: |
         gem install pact
            echo "export PATH=$(ruby -r rubygems -e 'puts Gem.bindir'):\$PATH" >> $GITHUB_ENV
            
      - name: Run Pact Provider Verification via Docker
        uses: addnab/docker-run-action@v3
        with:
            image: pactfoundation/pact-cli:latest
            options: --network=host -v ${{ github.workspace }}:/app -w /app
            run: |
               pact-provider-verifier ./pacts/FrontendApp-MockServer.json \
               --provider-base-url=http://localhost:4000
       
      - name: Run Schema Validation Tests
        run: npm run test:schema